### ISSUE TITLE
RS485 not working in charge control C board

### ISSUE THREAD

**Issue by VishuAVL** [chargebyte/everest-chargebyte#17]
Hi,
I have an issue with RS485 connection in board. When I am connecting IMD with the board and trying to read register value through everest, it is showing checksum value doesn't match but same thing is working in pc. I am attaching the screenshort of the error coming, can you tell me is it problem in accessing the port or we have to set something in our code. 

Thank You

![2024-12-13_16h24_46](https://github.com/user-attachments/assets/0ec32fc2-1f5a-4aba-a271-e06469b4b51b)

**Comment by VishuAVL** [comment]
Hi,
Thank you for the reply, it is false in the config file.

**Comment by mhei** [comment]
So, if you change it to `true` and restart the EVerest stack, is the issue then gone?

**Comment by VishuAVL** [comment]
Yeah, thank you issue is gone.
